name: tottouchordertastemobileapplication
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_animate: ^4.1.0
  pretty_dio_logger: ^1.4.0
  video_player: ^2.3.1
  flutter_svg: ^2.0.0
  lottie: ^2.3.2
  smooth_page_indicator: ^1.0.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  hive: ^2.2.3
  flutter_bloc: ^9.0.0
  http: ^1.2.2
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0
  shared_preferences: ^2.3.5
  crypto: ^3.0.6
  go_router: ^13.0.1
  mockito: ^5.4.5
  dio: ^5.4.0
  logging: ^1.3.0
  json_annotation: ^4.9.0
  image_picker: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/

fonts:
  - family: ShipporiMincho-Regular
    fonts:
      - asset: assets/fonts/ShipporiMincho-Regular.ttf
  - family: ShipporiMincho-Medium
    fonts:
      - asset: assets/fonts/ShipporiMincho-Medium.ttf
        weight: 500
  - family: ShipporiMincho-SemiBold
    fonts:
      - asset: assets/fonts/ShipporiMincho-SemiBold.ttf
        weight: 600
  - family: ShipporiMincho-Bold
    fonts:
      - asset: assets/fonts/ShipporiMincho-Bold.ttf
        weight: 700
